<a href="https://colab.research.google.com/github/gopikrishna7-hash/Data-Science-Implementation/blob/main/kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Collecting kaggle
  Downloading kaggle-2.2.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Collecting kagglesdk<1.0,>=0.1.30 (from kaggle)
  Downloading kagglesdk-0.1.34-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)
Downloading kaggle-2.2.3-py3-none-any.whl (111 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.5/111.5 kB 3.7 MB/s eta 0:00:00
Downloading kagglesdk-0.1.34-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.5/247.5 kB 12.5 MB/s eta 0:00:00
Installing collected packages: kagglesdk, kaggle
  Attempting uninstall: kagglesdk
    Found existing installation: kagglesdk 0.1.23
    Uninstalling kagglesdk-0.1.23:
      Successfully uninstalled kagglesdk-0.1.23
  Attempting uninstall: kaggle
    Found existing installation: kaggle 2.0.2
    Uninstalling kaggle-2.0.2:
      Successfully uninstalled kaggle-2.0.2
Successfully installed kaggle-2.2.3 kagglesdk-0.1.34

In [ ]:
import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_52454351d3a69ddf6ef87ac72291fb3d"

In [ ]:
!kaggle competitions list

ref                                                                           deadline             category         reward  teamCount  userHasEntered
----------------------------------------------------------------------------  -------------------  --------  -------------  ---------  --------------
https://www.kaggle.com/competitions/passenger-screening-algorithm-challenge   2017-12-15 23:59:00  Featured  1,500,000 Usd        518           False
https://www.kaggle.com/competitions/zillow-prize-1                            2018-01-10 15:59:00  Featured  1,200,000 Usd       3770           False
https://www.kaggle.com/competitions/data-science-bowl-2017                    2017-04-12 23:59:00  Featured  1,000,000 Usd       1972           False
https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection          2023-06-14 23:59:00  Featured  1,000,000 Usd       1249           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-3                  2026-11-02 23:59:00  Featured    850,000 Usd       1715           False
https://www.kaggle.com/competitions/arc-prize-2026-arc-agi-2                  2026-11-02 23:59:00  Featured    700,000 Usd       1142           False
https://www.kaggle.com/competitions/gemini-3                                  2025-12-12 23:59:00  Featured    500,000 Usd       4087           False
https://www.kaggle.com/competitions/openai-gpt-oss-20b-red-teaming            2025-08-26 23:59:00  Featured    500,000 Usd        601           False
https://www.kaggle.com/competitions/openai-to-z-challenge                     2025-06-29 23:59:00  Featured    500,000 Usd        225           False
https://www.kaggle.com/competitions/arc-prize-2026-paper-track                2026-11-09 23:59:00  Featured    450,000 Usd        101           False
https://www.kaggle.com/competitions/pokemon-tcg-ai-battle-challenge-strategy  2026-09-13 23:59:00  Featured    240,000 Usd        196           False
https://www.kaggle.com/competitions/llm-prompt-recovery                       2024-04-16 23:59:00  Featured    200,000 Usd       2175           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection      2026-02-27 23:59:00  Research    200,000 Usd       1391           False
https://www.kaggle.com/competitions/asl-fingerspelling                        2023-08-24 23:59:00  Research    200,000 Usd       1314           False
https://www.kaggle.com/competitions/second-annual-data-science-bowl           2016-03-14 23:59:00  Featured    200,000 Usd        192           False
https://www.kaggle.com/competitions/gemma-4-good-hackathon                    2026-05-18 23:59:00  Featured    200,000 Usd       1610           False
https://www.kaggle.com/competitions/kaggle-measuring-agi                      2026-04-16 23:59:00  Featured    200,000 Usd       1067           False
https://www.kaggle.com/competitions/datasciencebowl                           2015-03-16 23:59:00  Featured    175,000 Usd       1049           False
https://www.kaggle.com/competitions/data-science-bowl-2019                    2020-01-22 23:59:00  Featured    160,000 Usd       3493           False
https://www.kaggle.com/competitions/feedback-prize-2021                       2022-03-15 23:59:00  Featured    160,000 Usd       2058           False

In [ ]:
!kaggle competitions download -c titanic

Downloading titanic.zip to /content
100% 34.1k/34.1k [00:00<00:00, 47.4MB/s]

In [ ]:
!kaggle datasets download -d uciml/iris

Dataset URL: https://www.kaggle.com/datasets/uciml/iris
License(s): CC0-1.0
Downloading iris.zip to /content
100% 3.60k/3.60k [00:00<00:00, 9.13MB/s]

In [ ]:
!unzip iris.zip

Archive:  iris.zip
  inflating: Iris.csv
  inflating: database.sqlite

In [ ]:
!ls

database.sqlite  Iris.csv  iris.zip  sample_data  titanic.zip

In [ ]:
!pip install -q kagglehub

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mirichoi0218/insurance")

print( path)

Using Colab cache for faster access to the 'insurance' dataset.
/kaggle/input/insurance

In [ ]:
import pandas as pd
import os
df = pd.read_csv(os.path.join(path, "insurance.csv"))
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("aliiihussain/pubg-mobile-win-and-performance-prediction-dataset")

print("Path to dataset files:", path)
import pandas as pd
import os
df = pd.read_csv(os.path.join(path,"PUBG_Mobile_Win_Performance_Prediction_Dataset.csv"))
df.head()

Using Colab cache for faster access to the 'pubg-mobile-win-and-performance-prediction-dataset' dataset.
Path to dataset files: /kaggle/input/pubg-mobile-win-and-performance-prediction-dataset

,Player_ID,Map,Tier,Kills,Damage_Dealt,Survival_Time_Minutes,Headshot_Percentage,Assists,Revives,Distance_Travelled_km,Longest_Kill_meters,Heals_Used,Boosts_Used,Match_Rank,Win,Favorite_Weapon
0,P1,Sanhok,Platinum,4,441.86,22.70,6.13,1,3,7.54,5.27,4,0,76,0,UMP45
1,P2,Livik,Conqueror,1,551.58,5.58,33.86,1,3,7.80,85.31,2,3,55,0,M762
2,P3,Miramar,Conqueror,5,414.27,14.64,5.88,1,3,2.31,240.73,7,6,35,0,SCAR-L
3,P4,Erangel,Ace,3,499.70,18.00,35.07,5,4,7.77,272.42,1,1,62,0,M762
4,P5,Erangel,Platinum,7,751.11,29.13,38.39,4,0,2.72,62.02,8,6,9,0,Groza

In [ ]:
import kagglehub
import shutil
import os

# Download
path = kagglehub.dataset_download(
    "aliiihussain/pubg-mobile-win-and-performance-prediction-dataset"
)

# Destination in Colab
dest = "/content/pubg_dataset"

# Copy the entire dataset
shutil.copytree(path, dest, dirs_exist_ok=True)

print(os.listdir(dest))
print(path)

Using Colab cache for faster access to the 'pubg-mobile-win-and-performance-prediction-dataset' dataset.
['PUBG_Mobile_Win_Performance_Prediction_Dataset.csv']
/kaggle/input/pubg-mobile-win-and-performance-prediction-dataset

In [ ]:
import os
import pandas as pd

file = os.path.join(path, "PUBG_Mobile_Win_Performance_Prediction_Dataset.csv")
df = pd.read_csv(file)

df.head()

,Player_ID,Map,Tier,Kills,Damage_Dealt,Survival_Time_Minutes,Headshot_Percentage,Assists,Revives,Distance_Travelled_km,Longest_Kill_meters,Heals_Used,Boosts_Used,Match_Rank,Win,Favorite_Weapon
0,P1,Sanhok,Platinum,4,441.86,22.70,6.13,1,3,7.54,5.27,4,0,76,0,UMP45
1,P2,Livik,Conqueror,1,551.58,5.58,33.86,1,3,7.80,85.31,2,3,55,0,M762
2,P3,Miramar,Conqueror,5,414.27,14.64,5.88,1,3,2.31,240.73,7,6,35,0,SCAR-L
3,P4,Erangel,Ace,3,499.70,18.00,35.07,5,4,7.77,272.42,1,1,62,0,M762
4,P5,Erangel,Platinum,7,751.11,29.13,38.39,4,0,2.72,62.02,8,6,9,0,Groza

In [ ]:
df.head()

,Player_ID,Map,Tier,Kills,Damage_Dealt,Survival_Time_Minutes,Headshot_Percentage,Assists,Revives,Distance_Travelled_km,Longest_Kill_meters,Heals_Used,Boosts_Used,Match_Rank,Win,Favorite_Weapon
0,P1,Sanhok,Platinum,4,441.86,22.70,6.13,1,3,7.54,5.27,4,0,76,0,UMP45
1,P2,Livik,Conqueror,1,551.58,5.58,33.86,1,3,7.80,85.31,2,3,55,0,M762
2,P3,Miramar,Conqueror,5,414.27,14.64,5.88,1,3,2.31,240.73,7,6,35,0,SCAR-L
3,P4,Erangel,Ace,3,499.70,18.00,35.07,5,4,7.77,272.42,1,1,62,0,M762
4,P5,Erangel,Platinum,7,751.11,29.13,38.39,4,0,2.72,62.02,8,6,9,0,Groza

In [ ]:
df.iloc[2,5]=0

In [ ]:
print((df["Tier"]=="Conqueror").sum())

309

In [ ]:
import numpy as np
df.iloc[2,5]=np.nan

In [ ]:
from io import StringIO
import pandas as pd
data=""" col1,col2,col3,col4\n
1,2,3,4\n
num1,num2,num3\n
w,x,y,z """
stream=StringIO(data)
df=pd.read_csv(stream)
df.head()

   col1  col2  col3 col4
0     1     2     3    4
1  num1  num2  num3  NaN
2     w     x     y   z

In [ ]:
df.sort_values("Kills")

,Player_ID,Map,Tier,Kills,Damage_Dealt,Survival_Time_Minutes,Headshot_Percentage,Assists,Revives,Distance_Travelled_km,Longest_Kill_meters,Heals_Used,Boosts_Used,Match_Rank,Win,Favorite_Weapon
48,P49,Miramar,Bronze,2,477.19,7.04,53.05,4,0,2.58,283.14,0,2,52,0,DP-28
63,P64,Livik,Gold,2,525.33,26.80,56.27,3,3,6.43,12.94,9,0,92,0,AWM
1605,P1606,Sanhok,Conqueror,2,287.62,10.75,54.77,0,1,2.20,80.61,8,0,21,0,UMP45
1596,P1597,Miramar,Diamond,2,434.86,18.61,29.00,4,3,7.79,176.50,9,2,41,0,DP-28
1704,P1705,Livik,Bronze,2,332.98,8.99,14.69,2,3,5.97,127.88,4,6,83,0,UMP45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2405,P2406,Sanhok,Bronze,11,259.36,7.61,52.19,2,4,2.10,84.54,5,4,49,0,Groza
1333,P1334,Sanhok,Diamond,12,414.53,22.04,42.77,5,4,3.30,206.79,0,2,17,0,AWM
1593,P1594,Livik,Silver,13,531.85,20.87,16.91,1,0,7.20,225.68,7,2,85,0,AWM
1493,P1494,Sanhok,Bronze,13,442.02,8.47,29.83,0,2,0.75,252.58,3,1,71,0,Groza
2144,P2145,Sanhok,Silver,14,331.00,24.18,17.81,5,3,4.74,213.33,1,7,88,0,Groza

In [ ]:
q1=df["Damage_Dealt"].quantile(0.25)
q2=df["Damage_Dealt"].quantile(0.75)
iqr=q2-q1
lower=q1-1.5*iqr
upper=q2+1.5*iqr
print(df[(df["Damage_Dealt"] < lower) | (upper < df["Damage_Dealt"])])

     Player_ID      Map    Tier  Kills  Damage_Dealt  Survival_Time_Minutes  \
231       P232  Vikendi    Gold      4        866.49                  13.63
1147     P1148   Sanhok  Bronze      2        837.44                  15.30
1977     P1978  Vikendi     Ace      6        831.37                   7.79

      Headshot_Percentage  Assists  Revives  Distance_Travelled_km  \
231                 23.46        3        4                   6.92
1147                 9.04        2        0                   0.80
1977                28.77        3        4                   1.15

      Longest_Kill_meters  Heals_Used  Boosts_Used  Match_Rank  Win  \
231                246.90           6            7          65    0
1147               293.15           4            7          85    0
1977                71.12           1            2          26    0

     Favorite_Weapon
231            DP-28
1147            M416
1977           UMP45

In [ ]:
pd.pivot_table(
    df,
    values=["Damage_Dealt","Kills","Headshot_Percentage"],
    index="Tier",
    aggfunc="mean"
)

           Damage_Dealt  Headshot_Percentage     Kills
Tier
Ace          409.740574            32.510483  4.996979
Bronze       382.875728            32.351230  5.019417
Conqueror    403.388220            30.952395  4.770227
Crown        414.402388            33.481373  4.997015
Diamond      407.611821            31.785993  5.013245
Gold         410.640631            32.076013  4.916944
Platinum     398.498729            31.606421  4.979933
Silver       399.858057            32.209236  5.092357

In [ ]:
df.to_csv("pubg_details.csv",index=False)

In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["column1","column2","column3","column4"])
print(df)

      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df.to_csv("Random_nums.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int64
 1   column2  5 non-null      int64
 2   column3  5 non-null      int64
 3   column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [ ]:
  df[["column1","column2"]]

      column1  column2
row1        0        1
row2        4        5
row3        8        9
row4       12       13
row5       16       17

In [ ]:
df.describe()

         column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [ ]:
from io import StringIO
import pandas as pd
data=""" col1,col2,col3,col4\n
sam1,sam1,"hello! \\"Bob\\", is there any one"
1,2,3,4\n
num1,num2,num3\n
w,x,y,z """
stream=StringIO(data)

In [ ]:
df=pd.read_csv(stream,escapechar='\\')
df

   col1  col2           col3                col4
0  sam1  sam1  hello! \Bob\"   is there any one"
1     1     2              3                   4
2  num1  num2           num3                 NaN
3     w     x              y                  z

In [ ]:
df1=df.to_json("jsstream.json")
pd.read_json(df1)

ValueError: Invalid file path or buffer object type: <class 'NoneType'>

In [ ]:
df2=pd.read_csv("jsstream.json")
df2.to_json(orient="records")

'[]'